name: deploy style-guide
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  main:
    runs-on: ubuntu-latest
    container: platformos/testcafe:4.7.1-1.18.1
    strategy:
      max-parallel: 1
    env:
      MPKIT_EMAIL: ${{ secrets.MPKIT_EMAIL }}
      MPKIT_TOKEN: ${{ secrets.MPKIT_TOKEN }}
      MPKIT_URL: https://gp-styleguide.staging.oregon.platform-os.com
      CI: true
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Deploy
        shell: sh
        run: |
          set -e

          # capture current submodule versions
          git config --global --add safe.directory /__w/gp-style-guide/gp-style-guide
          git submodule > app/views/pages/index.txt.liquid
          # npm ci
          pos-cli deploy
